### ISSUE TITLE
CNN returns a -1 matrix as an output

### ISSUE THREAD

**Issue by Ignotus** [ralpguler/DenseReg#1]
Hi,

Thank you for making the source code publicly available.

Your CNN returns two matrices H, V of -1 values after net.forward() in the provided ipython notebook https://github.com/ralpguler/DenseReg/blob/master/DenseReg.ipynb (In [14]). I am wondering if correct model weights are provided since I have built your repository without any changes.

Best Regards,

Minh
[DenseReg.ipynb.zip](https://github.com/ralpguler/DenseReg/files/754777/DenseReg.ipynb.zip)

**Comment by ralpguler** [comment]
A build from scratch worked fine for me. 

All -1's means that all pixels are labelled as background. There might be a problem with your caffe installation. One thing to try would be to check if the "DeepLab" submodule works properly.

**Comment by Ignotus** [comment]
I have check `make runtest` on DeepLab and looks like it crashes on the DenseCRF layer:

https://gist.github.com/Ignotus/c556dd6606f281443c0c143dcabec6ff

I have tried both with CUDA 8 and CUDA 7.5, python2.7 and python3.4.

**Comment by ralpguler** [comment]
DenseCRF layer is not used in the DenseReg system, so you can ignore this error. Make sure that the DenseReg model is loaded properly. 

Also, you should be able to obtain Pascal VOC results within DeepLab without the crf layer(see the prototxts provided by them). You can check results to validate that DeepLab is working properly.

**Comment by Ignotus** [comment]
Could you specify CUDA, Python, libprotobuf, boost, opencv, glog version which you use? Looks like in my case after the first convolution it produces already something strange. I have checked and it returned an image of 64 channels, but values in each channels separately are the same. It's impossible since net.blobs['data'].data is a proper normalized by the mean value image.
