### ISSUE TITLE
Fail net.

### ISSUE THREAD

**Issue by WanteevNinja** [ralpguler/DenseReg#3]
Hello! Help me please with this issue. Jupyter fail running this code:
-----------------------------------------------------------------------------------------------------
# Load and resizethe image.
I = np.array( Image.open("I.png") )
New_size_x = np.int(8 * np.round(I.shape[0]/8.) + 1)
New_size_y = np.int(8 * np.round(I.shape[1]/8.) + 1)
I_resized = imresize(I,[New_size_x,New_size_y]).astype(np.float32)
# Subtract the mean value.
im = copy.deepcopy(I_resized[:,:,::-1])
im -= mean

im_input = np.transpose(im[:,:,::-1,np.newaxis], (3,2,0,1))
net.blobs['data'].reshape(*im_input.shape)
net.blobs['data'].data[...] = im_input
#Net is reshaped and input is set. now forward..
net.forward()

H= np.squeeze( copy.deepcopy(net.blobs['H_Out'].data[...] ) )
V= np.squeeze( copy.deepcopy(net.blobs['V_Out'].data[...] ) )

#Visualize
f, axarr = plt.subplots(1, 2, figsize=(9,8))
axarr[0].imshow(H)
axarr[1].imshow(V)
--------------------------------------------------------------------------------------------------------------------
I see this log in terminal:

I0615 16:59:01.569067  5440 net.cpp:283] Network initialization done.
I0615 16:59:01.648466  5440 net.cpp:816] Ignoring source layer data
I0615 16:59:01.648490  5440 net.cpp:816] Ignoring source layer weights_final_h_data_7_split
I0615 16:59:01.648494  5440 net.cpp:816] Ignoring source layer weights_final_v_data_8_split
I0615 16:59:01.648496  5440 net.cpp:816] Ignoring source layer weights_final_z_data_9_split
I0615 16:59:01.677593  5440 net.cpp:816] Ignoring source layer Face_Z
I0615 16:59:01.677647  5440 net.cpp:816] Ignoring source layer Regression_Z
I0615 16:59:01.677656  5440 net.cpp:816] Ignoring source layer Face_Z_zoom
I0615 16:59:01.677662  5440 net.cpp:816] Ignoring source layer Regression_Z_zoom
I0615 16:59:01.677666  5440 net.cpp:816] Ignoring source layer lossHorizontal
I0615 16:59:01.677671  5440 net.cpp:816] Ignoring source layer lossVertical
I0615 16:59:01.677675  5440 net.cpp:816] Ignoring source layer lossZ
I0615 16:59:01.677680  5440 net.cpp:816] Ignoring source layer loss_regression_h
I0615 16:59:01.677683  5440 net.cpp:816] Ignoring source layer loss_regression_v
I0615 16:59:01.677687  5440 net.cpp:816] Ignoring source layer loss_regression_z
F0615 16:59:06.245690  5440 blob.cpp:163] Check failed: data_ 

My CUDA version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

my Makefile.config:
----------------------------------------------------------------------------------------------------------------
## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
# USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
OPENCV_VERSION := 3

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /usr/include/python2.7 \
/home/lumius/.local/lib/python2.7/site-packages/numpy/core/include \
/usr/local/lib/python2.7/dist-packages/numpy/core/include \
/usr/local/lib/python2.7
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
# ANACONDA_HOME := $(HOME)/anaconda
# PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		# $(ANACONDA_HOME)/include/python2.7 \
		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial/
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial/

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @
------------------------------------------------------------------------------------
Is this normal that after initialization done some layers was ignoring?
DeepLab in your example successfully make and make pycaffe.
I really need a working prototype of your neural network, please, help me.

**Comment by ralpguler** [comment]
- The ignored layers are fine.

- Can you make sure the right caffe is used (sys.path.append... line in the notebok) and the caffe python layer that reads the data are using the correct caffe path.

**Comment by WanteevNinja** [comment]
Hm... path to caffe is right - it loaded to jupyter - sys.path.append("DeepLab-Context2/python")
Caffe python layer are using the correct caffe path - no doubt.
May be i need using my caffe, not Deeplab in your git? But how i can add the "interpolation layer" to my caffe? If i using my own caffe, all paths are right, but deploy file not read. Interpolation layer not found.

**Comment by ralpguler** [comment]
You can make sure the data read layer works on your caffe by removing everything after(including) interp layers in the deploy.prototxt.

To add the interp layer, copy
- src/caffe/layers/interp_layer.cpp
- src/caffe/util/interp.cpp
- src/caffe/util/interp.cu
- include/caffe/util/interp.hpp
- include/caffe/layers/interp_layer.hpp
- related parameter entry in caffe.proto.

Then make clean and make pycaffe again.

**Comment by WanteevNinja** [comment]
Big thanks! It works! God grant you big health!
